### ISSUE TITLE
Configuration to set service windows user

### ISSUE THREAD

**Issue by kakawait** [lean-delivery/ansible-role-jenkins-slave#9]
##### SUMMARY

Jenkins slave runner is executed on current local user. Could be great to override that value with specific user (seems to be supported by ansible https://docs.ansible.com/ansible/2.3/win_service_module.html)

```
slave_windows_service_user: foo
slave_windows_service_password: bar
```

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`tasks/Win32NT/service.yml`

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
```

**Comment by tgadiev** [comment]
@kakawait thanks for the contribution!
